# Generated by Django 5.0.4 on 2024-05-19 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_manage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='categories',
        ),
    ]
