# Generated by Django 5.0.4 on 2024-05-14 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products_manage.category'),
            preserve_default=False,
        ),
    ]
