# Generated by Django 5.0.4 on 2024-05-07 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_manage', '0002_remove_product_price_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reorder_point',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
