# Generated by Django 5.0.4 on 2024-04-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer_Management', '0001_initial'),
        ('products_manage', '0002_remove_product_price_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='purches',
            name='products',
            field=models.ManyToManyField(related_name='purches', to='products_manage.product'),
        ),
    ]
